version: 0.0
os: linux

files:
  - source: /MvcWeb
    destination: /var/www/MvcWeb
  - source: /RazorWeb
    destination: /var/www/RazorWeb

hooks:
  BeforeInstall:
    - location: scripts/stop_services.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_services.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_services.sh
      timeout: 60
      runas: root