version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Restoring .NET dependencies
      - dotnet restore

  build:
    commands:
      - echo Publishing MvcWeb and RazorWeb projects
      - dotnet publish MvcWeb/Ecom.Web.csproj --configuration Release --runtime linux-x64 --self-contained true -o ./publish/MvcWeb
      - dotnet publish RazorWeb/RazorWeb.csproj --configuration Release --runtime linux-x64 --self-contained true -o ./publish/RazorWeb
      - echo Copying appspec.yml to publish directories
      - cp appspec.yml ./publish/MvcWeb
      - cp appspec.yml ./publish/RazorWeb
      - cp appspec.yml ./publish
      - echo Build directory structure for verification
      - ls -R ./publish

  post_build:
    commands:
      - echo Running tests
      - dotnet test --configuration Release

artifacts:
  files:
    - "publish/**/*"
    - "scripts/*"
  discard-paths: no