version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 8.0
        commands:
            - echo Restoring .NET dependencies
            - dotnet restore

    build:
        commands:
            - echo Directory structure
            - ls
            - echo Publishing the .NET project for deployment
            - dotnet publish DemoApp.csproj --configuration Release --runtime linux-x64 --self-contained true -o ./publish
            - echo Copying appspec.yml to publish directory
            - cp appspec.yml ./publish
            - echo Build directory structure for verification
            - ls -R ./publish

    post_build:
        commands:
            - echo Running tests
            - dotnet test --configuration Release

artifacts:
    files:
        - "publish/**/*"
    discard-paths: no
